
context("format_big_n")

test_that("check format_big_n with valid positive inputs", {
  function_output <- format_big_n(123)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123")
  function_output <- format_big_n(1234)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "1.23 K")
  function_output <- format_big_n(12345)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "12.35 K")
  function_output <- format_big_n(123456)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.46 K")
  function_output <- format_big_n(1234567)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "1.23 M")
  function_output <- format_big_n(12345678)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "12.35 M")
  function_output <- format_big_n(123456789)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.46 M")
  function_output <- format_big_n(1234567890)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "1.23 B")
  function_output <- format_big_n(12345678901)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "12.35 B")
  function_output <- format_big_n(123456789012)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.46 B")
  function_output <- format_big_n(1234567890123)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "1.23 T")
  function_output <- format_big_n(12345678901234)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "12.35 T")
  function_output <- format_big_n(123456789012345)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.46 T")
  function_output <- format_big_n(1234567890123456)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "1234.57 T")
})

test_that("check format_big_n with valid negative inputs", {
  function_output <- format_big_n(-123)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-123")
  function_output <- format_big_n(-1234)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-1.23 K")
  function_output <- format_big_n(-12345)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-12.35 K")
  function_output <- format_big_n(-123456)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-123.46 K")
  function_output <- format_big_n(-1234567)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-1.23 M")
  function_output <- format_big_n(-12345678)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-12.35 M")
  function_output <- format_big_n(-123456789)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-123.46 M")
  function_output <- format_big_n(-1234567890)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-1.23 B")
  function_output <- format_big_n(-12345678901)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-12.35 B")
  function_output <- format_big_n(-123456789012)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-123.46 B")
  function_output <- format_big_n(-1234567890123)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-1.23 T")
  function_output <- format_big_n(-12345678901234)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-12.35 T")
  function_output <- format_big_n(-123456789012345)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-123.46 T")
  function_output <- format_big_n(-1234567890123456)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "-1234.57 T")
})

test_that("check format_big_n with different digits", {
  function_output <- format_big_n(123456789, digits = -3)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "0 M")
  function_output <- format_big_n(123456789, digits = -2)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "100 M")
  function_output <- format_big_n(123456789, digits = -1)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "120 M")
  function_output <- format_big_n(123456789, digits = 0)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123 M")
  function_output <- format_big_n(123456789, digits = 1)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.5 M")
  function_output <- format_big_n(123456789, digits = 2)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.46 M")
  function_output <- format_big_n(123456789, digits = 3)
  expect_equal(class(function_output), "character")
  expect_true(function_output == "123.457 M")
})

test_that("check format_big_n with wrong input", {
  expect_error(
    format_big_n("potato")
  )
  expect_error(
    format_big_n(list())
  )
  expect_error(
    format_big_n(
      x = 123456789,
      digits = "potato"
    )
  )
  expect_error(
    format_big_n(
      x = 123456789,
      digits = list()
    )
  )
  expect_error(
    format_big_n(
      x = 123456789,
      digits = 0.5
    )
  )
})
